version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.6
    commands:
      - pip3 install -r requirements.txt
      - echo Installing dependencies


  build:
    commands:
      - python3 manage.py makemigrations
      - python3 manage.py migrate
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'