version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python3.7 -m pip install --upgrade pip
      - pip3 install virtualenv
      - virtualenv env
      - source env/bin/activate
      - pip3 install -r requirements.txt
      - echo Installing dependencies


  build:
    commands:
#      - python3.7 manage.py makemigrations
#      - python3.7 manage.py migrate
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'