# Generated by Django 3.2.9 on 2022-04-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_post_viewed'),
        ('chat', '0005_alter_chatgroup_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to='products.post'),
        ),
    ]
