# Generated by Django 3.2.9 on 2022-04-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='buyer_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
