# Generated by Django 3.2.9 on 2022-04-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_post_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewed',
        ),
    ]
