# Generated by Django 3.2.9 on 2022-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220516_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.CharField(blank=True, max_length=250, null=True)),
                ('viewer_user_id', models.IntegerField(blank=True, null=True)),
                ('viewer_username', models.CharField(blank=True, max_length=100, null=True)),
                ('viewer_user_avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('post_created_date', models.CharField(blank=True, max_length=250, null=True)),
                ('post_username', models.CharField(blank=True, max_length=250, null=True)),
                ('post_user_avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('post_user_id', models.IntegerField(blank=True, null=True)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, choices=[('view', 'View'), ('expire', 'Expire'), ('add', 'Add')], max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created'],
            },
        ),
    ]
