# Generated by Django 3.2.9 on 2022-05-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_expire',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('moderated', 'Moderated')], default='active', max_length=50, null=True),
        ),
    ]
